name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Project Version
        id: get_version
        run: |
          CLEAN_VERSION=$(./gradlew properties --no-daemon | grep "^version:" | awk '{print $2}')
          echo "MOD_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "Detected version: $CLEAN_VERSION"

      - name: Read Changelog
        id: changelog
        run: |
          if [ -f Changelog.md ]; then
            {
              echo 'CHANGELOG_CONTENT'
              cat Changelog.md
              echo 'EOF'
            } >> "$GITHUB_ENV"
          else
            echo "CHANGELOG_CONTENT=Ğ¡Ğ¿Ğ¸ÑĞ¾Ğº Ğ¸Ğ·Ğ¼ĞµĞ½ĞµĞ½Ğ¸Ğ¹ Ğ½Ğµ Ğ¿Ñ€ĞµĞ´Ğ¾ÑÑ‚Ğ°Ğ²Ğ»ĞµĞ½." >> "$GITHUB_ENV"
          fi

      - name: Build with Gradle
        run: ./gradlew build

      - name: Cleanup extra jars
        run: rm -f build/libs/*-dev.jar build/libs/*-sources.jar build/libs/*-shadow.jar

      - name: Create Automated Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.MOD_VERSION }}
          name: "Sakuraland v${{ env.MOD_VERSION }}"
          body: |
            # [ğŸŒ¸] ĞĞ²Ñ‚Ğ¾Ğ¼Ğ°Ñ‚Ğ¸Ñ‡ĞµÑĞºĞ°Ñ ÑĞ±Ğ¾Ñ€ĞºĞ° Ğ¼Ğ¾Ğ´Ğ° Ğ´Ğ»Ñ ÑĞµÑ€Ğ²ĞµÑ€Ğ° SakuraLand [ğŸŒ¸]
            ** [ğŸ“] Ğ’ĞµÑ€ÑĞ¸Ñ Ğ¼Ğ¾Ğ´Ğ°:** `${{ env.MOD_VERSION }}` **[ğŸ“]**
            
            ### [ğŸ“œ] Ğ¡Ğ¿Ğ¸ÑĞ¾Ğº Ğ¸Ğ·Ğ¼ĞµĞ½ĞµĞ½Ğ¸Ğ¹: [ğŸ“œ]
            ${{ env.CHANGELOG_CONTENT }}
            
            # [ğŸ”§] Ğ¢Ğ•Ğ¥ĞĞ˜Ğ§Ğ•Ğ¡ĞšĞĞ¯ Ğ˜ĞĞ¤ĞĞ ĞœĞĞ¦Ğ˜Ğ¯ [ğŸ”§]
            **Ğ’ĞµÑ‚ĞºĞ°:** `${{ github.ref_name }}`
            **ĞšĞ¾Ğ¼Ğ¼Ğ¸Ñ‚:** `${{ github.sha }}`
          prerelease: true
          draft: false
          files: build/libs/*.jar
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}